<template>
  <picture>
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-taxi-service-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700&format=webp')
      "
      type="image/webp"
    />
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-taxi-service-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700')
      "
      type="image/jpg"
    />
    <img
      :src="
        require('~/assets/justaxis-glastonbury-taxi-service-somerset-700w.jpg')
      "
      width="700"
      height="351"
      loading="lazy"
      alt="Taxi Company for Glastonbury, Street, Wells and whole of Somerset"
    />
  </picture>
</template>
