<template>
  <picture>
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-taxi-service-2-1340w.jpg?resize&sizes[]=700&sizes[]=1024&sizes[]=1340&format=webp')
      "
      type="image/webp"
    />
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-taxi-service-2-1340w.jpg?resize&sizes[]=1340')
      "
      type="image/jpg"
    />
    <img
      :src="require('~/assets/justaxis-glastonbury-taxi-service-2-1340w.jpg')"
      width="1340"
      height="474"
      class="hero-img"
      alt="JusTaxis Taxi Company Glastonbury, Somerset"
    />
  </picture>
</template>
