<template>
  <picture>
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-town-hall-pickup-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700&format=webp')
      "
      type="image/webp"
    />
    <source
      :srcSet="
        require('~/assets/justaxis-glastonbury-town-hall-pickup-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700')
      "
      type="image/jpg"
    />
    <img
      :src="require('~/assets/justaxis-glastonbury-town-hall-pickup-700w.jpg')"
      width="700"
      height="700"
      alt="JusTaxis Taxi picking up at Glastonbury Town Hall in Somerset"
    />
  </picture>
</template>
