<template>
  <picture>
    <source
      :srcSet="
        require('~/assets/about/taxis-street-glastonbury-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700&format=webp')
      "
      type="image/webp"
    />
    <source
      :srcSet="
        require('~/assets/about/taxis-street-glastonbury-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700')
      "
      type="image/jpg"
    />
    <img
      :src="
        require('~/assets/about/taxis-street-glastonbury-somerset-700w.jpg')
      "
      width="700"
      height="566"
      class="polaroid"
      alt="JusTaxis Taxi Service covering Glastonbury, Street, Wells and the whole of Somerset"
      loading="lazy"
    />
  </picture>
</template>
