<template>
  <picture>
    <source
      :srcSet="
        require('~/assets//about/justaxis-glastonbury-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700&format=webp')
      "
      type="image/webp"
    />
    <source
      :srcSet="
        require('~/assets//about/justaxis-glastonbury-somerset-700w.jpg?resize&sizes[]=375&sizes[]=500&sizes[]=700')
      "
      type="image/jpg"
    />
    <img
      :src="require('~/assets//about/justaxis-glastonbury-somerset-700w.jpg')"
      width="700"
      height="376"
      class="polaroid"
      alt="Justin and Dawn Miller from JusTaxis Glastonbury, Somerset"
      loading="lazy"
    />
  </picture>
</template>
